-- Profile
CREATE TABLE IF NOT EXISTS profile (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name_ja VARCHAR(255),
  name_en VARCHAR(255),
  title_ja VARCHAR(255),
  title_en VARCHAR(255),
  affiliation_ja VARCHAR(255),
  affiliation_en VARCHAR(255),
  lab_ja VARCHAR(255),
  lab_en VARCHAR(255),
  summary_ja TEXT,
  summary_en TEXT,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS profile_skills (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  profile_id BIGINT UNSIGNED NOT NULL,
  skill_ja VARCHAR(255),
  skill_en VARCHAR(255),
  sort_order INT,
  FOREIGN KEY (profile_id) REFERENCES profile(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Projects
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  title_ja VARCHAR(255),
  title_en VARCHAR(255),
  description_ja TEXT,
  description_en TEXT,
  link_url VARCHAR(512),
  year INT,
  published TINYINT(1) DEFAULT 1,
  sort_order INT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS project_tech_stack (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  label VARCHAR(128) NOT NULL,
  sort_order INT,
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Research
CREATE TABLE IF NOT EXISTS research (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  title_ja VARCHAR(255),
  title_en VARCHAR(255),
  summary_ja TEXT,
  summary_en TEXT,
  content_md_ja LONGTEXT,
  content_md_en LONGTEXT,
  year INT,
  published TINYINT(1) DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Meetings
CREATE TABLE IF NOT EXISTS meetings (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  meeting_at DATETIME NOT NULL,
  duration_minutes INT NOT NULL,
  meet_url VARCHAR(512),
  calendar_event_id VARCHAR(255),
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_meetings_meeting_at (meeting_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blacklist (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL UNIQUE,
  reason VARCHAR(255),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schedule_blackouts (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Blogs
CREATE TABLE IF NOT EXISTS blog_posts (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  title_ja VARCHAR(255),
  title_en VARCHAR(255),
  summary_ja TEXT,
  summary_en TEXT,
  content_md_ja LONGTEXT,
  content_md_en LONGTEXT,
  published TINYINT(1) DEFAULT 0,
  published_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS blog_post_tags (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  post_id BIGINT UNSIGNED NOT NULL,
  tag VARCHAR(64) NOT NULL,
  sort_order INT,
  FOREIGN KEY (post_id) REFERENCES blog_posts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Contact messages
CREATE TABLE IF NOT EXISTS contact_messages (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  topic VARCHAR(255),
  message TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
